baseURL = "http://teremokdaycare.com"
languageCode = "en-us"
title = "TEREMOK | In-home Daycare"
theme = "navigator-hugo"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6
    
    # Footer Service Menu
    [[menu.service]]
        name    = "Graphic Design"
        url     = "/service"
        weight  = 1
    [[menu.service]]
        name    = "Web Design"
        url     = "/service"
        weight  = 2
    [[menu.service]]
        name    = "Web Development"
        url     = "/service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Partners"
        url     = "/about"
        weight  = 1
    [[menu.quicklink]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.quicklink]]
        name    = "FAQ's"
        url     = "/about"
        weight  = 3
    [[menu.quicklink]]
        name    = "Badges"
        url     = "/about"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    footerDescription = "config -- footerDescription"

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "Designed like home to feel like home"
        description = "\"85% of brain growth occurs in the first 3 years of life\" - University of Kentucky, National Research Network [click for more info]"
        descUrl = "http://www.bwgresnet.res.ku.edu/wp-content/uploads/2015/11/TWMB-1.pdf"
        description2 = "We provide quality education and development for children aged 1 - 4 to help foster brain growth."
        button  = true
        btnText = "More about our program"
        btnURL  = "/about"
        img = "images/home/main.jpg"

    # About 2 Section
    [params.aboutSm]
        enable  = false
        title   = "We have explored the digital landscape with passion for a long time"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Prepare Your Children Together!"
        subtitle= ""
        btnText = "Contact Us"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "We are located in Kensington, MD - close enough to the i-270/i-495 spur to make it convenient for parents during their commute, yet far enough from it to provide tranquility for the kids."
        address = "3404 McComas Ave. <br>Kensington, Maryland 20895"
        phone   = "(301) 332 - 8966"
        facebook= "https://www.facebook.com/daycare.kensington/"
        mapLatitude = "39.033281"
        mapLongitude= "-77.068965"
        mapMarker   = "images/marker.png"
