theme = "hugo-serif-theme"
baseURL = "/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[Languages]
    [Languages.en]
        languageCode = "en-us"
        languageName = "English site"
        title = "Teremok Daycare"
        contentDir = "content/en"
        weight = 1
    [Languages.ru]
        languageCode = "ru"
        languageName = "Русский сайт"
        title = "Детский Садик Теремок"
        contentDir = "content/ru"
        weight = 2

[params]
    google_analytics_id=""

[[menu.main]]
	name = "home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "schedule"
    url = "/schedule/"
    weight = 2

[[menu.main]]
    name = "gallery"
    url = "/gallery/"
    weight = 3

[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 4